{
 "title": "Search Engine Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "DB Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB Size",
   "type": "table",
   "description": "DB Size",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT pg_size_pretty( pg_database_size('postgres') );\n"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "table",
   "description": "Table Size",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT pg_size_pretty( pg_total_relation_size('search_terms') );"
    }
   ]
  },
  {
   "title": "Count of Search Terms",
   "type": "stat",
   "description": "Count of Search Terms",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(id) FROM search_terms "
    }
   ]
  },
  { "title": "Search Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Seach Terms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(searchByTerm_total{term=~\".*\"}) by (term)"
    }
   ]
  },
  {
   "title": "Response Time By Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{status=\"200\", uri=\"/search\"}/http_server_requests_seconds_count{status=\"200\", uri=\"/search\"}"
    }
   ]
  },
  {
   "title": "Application Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_sum{status=\"200\", uri=\"/search\"})/sum(http_server_requests_seconds_count{status=\"200\", uri=\"/search\"})"
    }
   ]
  }
 ]
}